### ISSUE TITLE
Copy path to clipboard should copy query parameter state even if file has not been saved

### ISSUE THREAD

**Issue by jessegrosjean** [FoldingText/foldingtext-for-atom#28]

**Comment by RobTrew** [comment]
The URL queries and Edit > Copy Path are excellent. Thank you.

Not sure if this is a thought for an extension of `copyPathToClipboard()` or for a sibling `copyBookmarkToClipboard()`, but even in cases where there is no hoisting or filtering, it might be useful to simply be able to copy to clipboard a query just for the current **selection** (list of ids).

**Comment by jessegrosjean** [comment]
I've decided to just include the selection when copyPathToClipboard instead of having a separate command.
