### ISSUE TITLE
Ability to disable animations

### ISSUE THREAD

**Issue by jackbrannen** [FoldingText/foldingtext-for-atom#41]
One of my favorite features of plain-text workflows is the speed. The little animations in Atom make the whole thing feel laggy to me. Examples:
- Indenting and outdenting text
- Moving lines up and down

**Comment by jackbrannen** [comment]
Sorry, ignorant GitHub question: I think can't assign this to any milestone. I assume that is your job, Jesse, but if not, let me know.

**Comment by jessegrosjean** [comment]
This is actually already possible, though a bit hidden:

Atom > Preferences > Packages > FoldingText for Atom > Settings > Disable Animation
