### ISSUE TITLE
Keybindings don't work in Windows

### ISSUE THREAD

**Issue by juranta** [FoldingText/foldingtext-for-atom#45]
Many of the most important FoldingText keybindings use `cmd` key. Windows OS/computers don't have a `cmd` key, so these keybindings don't work in Windows Atom. I created a custom keybinding for each command, where I changed `cmd` to `ctrl`. For instance, in Sublime Text where you'd use `cmd` in OS X, it's often `ctrl` in Windows`.

**Comment by jessegrosjean** [comment]
Glad to here you are trying this out on windows as you can see I haven't done any testing there yet. Could you post the keybindings that you are using?

**Comment by juranta** [comment]
I basically replaced all `cmd`with `ctrl`. The result is below. Atom follows Sublime Text closely. The way it's done in Sublime Text is that, generally, `cmd` in Mac is the same as `ctrl` in in Windows. There are probably many other guidelines out there, but as a general rule I guess when going multi-platform with Atom and Sublime text, it's best to follow the keybinding structure they used. 

Oh, and the `ctrl+t`(for tags) keybinding did not work. I'm not sure if it was some lack in my quick attention or some other issue.

```
# Sublime Parity
'ctrl-a': 'core:select-all'
'ctrl-k ctrl-u': 'editor:upper-case'
'ctrl-k ctrl-l': 'editor:lower-case'
'ctrl-l': 'editor:select-line'
'ctrl-enter': 'editor:newline-below'
'ctrl-shift-enter': 'editor:newline-above'
'ctrl-]': 'editor:indent-selected-rows'
'ctrl-[': 'editor:outdent-selected-rows'
'ctrl-up': 'editor:move-line-up'
'ctrl-down': 'editor:move-line-down'
'ctrl-left': 'editor:outdent-selected-rows'
'ctrl-right': 'editor:indent-selected-rows'

'alt-ctrl-g': 'outline-editor:group-items'

'ctrl-j': 'editor:join-lines'
'ctrl-D': 'editor:duplicate-lines'
'ctrl-L': 'editor:split-selections-into-lines'

'ctrl-alt-[': 'editor:fold-current-row'
'ctrl-alt-]': 'editor:unfold-current-row'
'ctrl-alt-{': 'editor:fold-all' # Atom Specific
'ctrl-alt-}': 'editor:unfold-all' # Atom Specific
'ctrl-k ctrl-0': 'editor:unfold-all'
'ctrl-k ctrl-1': 'editor:fold-at-indent-level-1'
'ctrl-k ctrl-2': 'editor:fold-at-indent-level-2'
'ctrl-k ctrl-3': 'editor:fold-at-indent-level-3'
'ctrl-k ctrl-4': 'editor:fold-at-indent-level-4'
'ctrl-k ctrl-5': 'editor:fold-at-indent-level-5'
'ctrl-k ctrl-6': 'editor:fold-at-indent-level-6'
'ctrl-k ctrl-7': 'editor:fold-at-indent-level-7'
'ctrl-k ctrl-8': 'editor:fold-at-indent-level-8'
'ctrl-k ctrl-9': 'editor:fold-at-indent-level-9'
'ctrl-.': 'outline-editor:toggle-fold-items'
'shift-ctrl-.': 'outline-editor:toggle-fully-fold-items'

'ctrl-alt-down': 'outline-editor:hoist',
'ctrl-alt-up': 'outline-editor:unhoist',

'ctrl-b': 'outline-editor:toggle-bold'
'ctrl-i': 'outline-editor:toggle-italic'
'ctrl-u': 'outline-editor:toggle-underline'
'ctrl-C': 'outline-editor:toggle-code'
'ctrl-k': 'outline-editor:toggle-strikethrough'
'ctrl-K': 'outline-editor:edit-link'
```

**Comment by jessegrosjean** [comment]
@juranta Probably will still need some work as I'm not to familiar with appropriate Windows keybindings. But this f329505 should at least be a good start.
