### ISSUE TITLE
Following links to non-text local files opens an empty pane in Atom

### ISSUE THREAD

**Issue by RobTrew** [FoldingText/foldingtext-for-atom#60]
Following links to non text files such as PDF results in the opening of an empty Atom editing pane.

If it looks feasible, it would be good to trap the handling of these links and perhaps open the relevant folder window (selecting the file) in the local file browser (OS X Finder, etc).

**Comment by jessegrosjean** [comment]
I don't know how to solve this generally, since Atom is an extensible platform it's possible that you might want to open any file in it. I think instead I'll add "Open Link with Finder" and "Show Link in Finder" context menu items when you right click on a link. Sound good?

**Comment by RobTrew** [comment]
Thanks – sounds good …
