### ISSUE TITLE
outline mode

### ISSUE THREAD

**Issue by kofifus** [FoldingText/foldingtext-for-atom#8]
I've been reading the doc
http://jessegrosjean.gitbooks.io/foldingtext-for-atom-user-s-guide/content/editing.html

I don't understand how to enter outline mode ?
(you may want to modify this doc page to explain that)

Thx!

**Comment by jessegrosjean** [comment]
It's in there right after "To escape to outline mode:". The trick is to press the "Escape" key. When you do that the item that you were selecting becomes "fully" selected, like a menu item interface. Does that help?

**Comment by jessegrosjean** [comment]
I'm going to close this for now, but please let me know if you still can't get it to work.
