### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by idike** [FoldingText/foldingtext-for-atom#84]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-element.js:58:18)
ft-text-input.performLayout (/Users/idike/.atom/packages/foldingtext-for-atom/lib/extensions/ui/text-input-element.coffee:275:52)
<unknown> (/Users/idike/.atom/packages/foldingtext-for-atom/lib/extensions/ui/text-input-element.coffee:228:26)
```

**Comment by iOrevir** [comment]
Just installed the package and got this issue three times (mentioned in the deprecated calls). 
What are the implications of this issue?

**Comment by jessegrosjean** [comment]
Sorry I'm not sure, but I "think" it would only effect styling. Maybe broken styles.
