### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by Annis-Monadjem** [FoldingText/foldingtext-for-atom#88]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (/usr/share/atom-beta/resources/app/src/text-editor-element.js:13:10)
HTMLElement.performLayout (/home/sky/.atom/packages/foldingtext-for-atom/lib/extensions/ui/text-input-element.coffee:275:51)
<unknown> (/home/sky/.atom/packages/foldingtext-for-atom/lib/extensions/ui/text-input-element.coffee:228:26)
```

**Comment by kerim** [comment]
Any update on this?

**Comment by Annis-Monadjem** [comment]
Hi Kerim, i'm not using atom. The above messages must have been auto generated and published by by Atom, while i was testing it some time ago. I gave up on atom, as it is extremely slow for my work. Good luck.
